### ISSUE TITLE
Create new component

### ISSUE THREAD

**Issue by dgsunesen** [sinnerschrader/aem-react#1]
Hi there. I'm trying to adopt your way of integrating React with AEM, but I'm struggling a bit with creating new components. 

What is the best way of creating a new component and get it deployed to AEM? 
What is the best workflow of getting changes from AEM and back out again into your development environment/files?

I tried to create a new component (just dublicating the 'text' component) within `demo/src/main/content/jcr_root/apps/react-demo/components` and my `watch` task starts running and a new component gets created within my AEM instance. However, that components `jcr:primaryType` is set to `sling Folder`

The only way I got a new component installed properly was by running the `mvn clean install -PautoInstallPackage` task but that sort of resets the changes I've made through e.g. the Edit view.

I would like some guidance on how the workflow should be setup for this to work properly both dev environment > AEM and AEM > dev environment.

I'm sitting on a Mac using Sublime Text outside of AEM.

Best regards,
Dan

**Comment by stemey** [comment]
There are some issues with the webdav synchronization. The following artifacts are not properly handled and you need to use the maven task as you did:
- dialog.xml
- .content.xml
- possibly more

It does work fine for:
- templates like sly and jsps
- changes in typescript

**Comment by dgsunesen** [comment]
Alright. Thanks for a quick answer. Got any time horizon on the synchronization?

Would be more than happy to do some sparring on this if needed. I'm currently working on a large scale project where we are trying to implement this, so if I in any way can help on this or bring in any ideas on the table, let me know :)

**Comment by stemey** [comment]
If you have a synchronization solution that handles all kinds of data similarly well, then I am very interested to hear about it. I believe that the webdav synchronization issues are due to a problem in the AEM implementation of the webdav server. The watch task simply uses existing functionality. I have had a look at other options like vault and sling file installer (https://sling.apache.org/documentation/bundles/file-installer-provider.html) but have not yet found an ideal solution.

Any other suggestions concerning the workflow are welcome :)

**Comment by dgsunesen** [comment]
So the workflow we are currently looking at is for developers to have their own AEM locally installed and be able to use whatever editor they want. They should be able to create AEM/React components from outside of AEM and be able to deploy/push them into AEM (like using the `maven` task). But we are also looking at ways for content being created in AEM to be pushed backwards, so let's say you edit something within your component on the AEM side (e.g. text, images) that new content should be synchronized backwards so that we prevent overriding existing components.

**Comment by stemey** [comment]
I agree that developers should use their tool of choice and push "code" via `maven` or `node` into a running local AEM instance. We usually use `npm run watch` for most code and resort to `maven` in those cases mentioned before.

Syncing content back from AEM into local file system seems to make sense for me in only special cases:
- the component design `resourcetype=wcm/core/components/designer` which is usually located in `/etc/designs/your-project/jcr:content` is best edited via the AEM ui.
- TBD

General content under '/content' is usually not synced back into the local java project but is usually exported into a content package. 
If content should not be created manually on each environment but rather automatically when a new version of software is deployed, then we use a migration tool which works similar to [flyway](https://flywaydb.org/). It checks the software version stored in the content against the bundle's version and runs necessary migration tasks. These task can be as simple as installing content packages programatically. This tool can be contributed if you are interested.

**Comment by dgsunesen** [comment]
That sounds interesting, would love to see that.

**Comment by dgsunesen** [comment]
Since this issue ticket is evolving into more of a Q/A, I might just continue with that, if you don't mind. 

How do you get your routes to work within AEM? And what about dragging react components into another react component? I mean, say you have component A and you drag and drop component B into within the AEM edit mode, how would component A know of component B's existence within the actual react code?

**Comment by stemey** [comment]
1. Dnd react components
With release 0.2.1 there is a generic parys component written in react which integrates react children into the react tree.

2. Routes
In my opinion routes require that react components can initialize their state by loading data from the server. Otherwise their usage is really limited. The current approach is based on the react state originating from the root component's jcr resource. Currently we are working on this issue by integrating redux, which makes it possible to replace the static jcr resource by redux state which can be modified from within the components. Main advantage of using redux is that the state of the whole tree can be sent down to the react component from the server.

**Comment by dgsunesen** [comment]
So how would go on about making transitions and state handling between different routes?

**Comment by stemey** [comment]
If all the data for the different routes is available in the component's jcr resource you should be able to use React router for server and client side rendering. If you map routes to content different pages in AEM then you are out of luck with the current solution. As already mentioned, we are looking into this in 0.3.

**Comment by dgsunesen** [comment]
Another question: how do I work around having all my default state properties live inside of `Container.tsx` ?

**Comment by stemey** [comment]
'Container.tsx' is not a really good abstraction and will be removed soon. If you are using accordion from the demo package you should extend accordion and overwrite the constructor. You can set the default state in the constructor and initialize it from props like "initialActiveIndex".

**Comment by dgsunesen** [comment]
Alright. I'll try that out. Can you quickly explain the idea behind the `path` property that you need to provide each component?
