### ISSUE TITLE
why it's empty jsx file in React component?

### ISSUE THREAD

**Issue by Json-w** [sinnerschrader/aem-react#22]
hi,

I want to know why there is empty jsx files in React component?
 
And when I follow the document, I got an error.
![image](https://cloud.githubusercontent.com/assets/7090689/21832643/8223365e-d7e7-11e6-8026-6a9c7a1bda7e.png)

**Comment by Json-w** [comment]
Symbolic Name	demoapp.core
Version	1.0.0.SNAPSHOT
Bundle Location	jcrinstall:/apps/demoapp/install/demoapp.core-1.0-SNAPSHOT.jar

The status of this bundle is always installed

**Comment by Json-w** [comment]
below is the bundle error:
org.osgi.framework.BundleException: Unresolved constraint in bundle demoapp.core [504]: Unable to resolve 504.1: missing requirement [504.1] osgi.wiring.package; (&(osgi.wiring.package=com.sinnerschrader.aem.react.exception)(version>=0.3.0)(!(version>=1.0.0))) [caused by: Unable to resolve 496.0: missing requirement [496.0] osgi.wiring.package; (&(osgi.wiring.package=org.apache.commons.lang3)(version>=3.3.0)(!(version>=4.0.0)))]

**Comment by stemey** [comment]
You should install the last stable version of aem-react from maven central:
http://repo1.maven.org/maven2/com/sinnerschrader/aem/react/demo/0.4.0/

The jsx file is just a placeholder, while the actual react component is located in javascript source folder. The react components are written in Typescript or es6 and need node tools to generate the plain javascript file in es5.

**Comment by Json-w** [comment]
Thank you for your response.
I try to install the 0.4.0 package which you provided.
But it still not works ,it missd the dependencies.
<img width="1198" alt="screen shot 2017-01-12 at 11 01 28 pm" src="https://cloud.githubusercontent.com/assets/7090689/21895256/fb5bfae8-d91c-11e6-899e-3387808f97e8.png">
![Uploading Screen Shot 2017-01-12 at 11.01.51 PM.png…]()

**Comment by SaurabhSriDev** [comment]
1. You need to add 3.0.1 version for first err in aem-react/pom.xml -
```
<dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        <!--<version>3.3.2</version>-->
		<version>3.0.1</version> 
		<scope>provided</scope>
      </dependency>
```

2. download org.apache.sling.commons.json-2.0.18.jar and install it manually through http://localhost:4502/system/console/bundles.

**Comment by stemey** [comment]
Thanks for finding out about this.
I will look into it, because the commons-lang is supposed to be an embedded dependency and there should not be a problem.

**Comment by stemey** [comment]
I cleaned up the dependencies - you still nedd to upload those bundles manually.
