### ISSUE TITLE
Is in place editing possible with this library?

### ISSUE THREAD

**Issue by bearcherian** [sinnerschrader/aem-react#23]
I can't seem to find any example/demo code that shows this or enables this. We are trying to implement multiple in-place editors within react components as documented here:
https://docs.adobe.com/docs/en/aem/6-2/develop/components/multiple-inplace-editors.html

**Comment by stemey** [comment]
Currently there is no demo for this. The simple solution is to include a non-react aem component with an inline-editable text. A more advanced solution is to implement the features of <cq:text/> or its sightly equivalent in a react component. Maybe this only requires rendering appropriate classes in author mode. But you probably have to add more. Please post the rendered html from an inline editable text in author mode and we can find a solution. We might have to add delegate rendering the html to the java code and then include it as _dangerouslySetInnerHtml.

**Comment by stemey** [comment]
Looks like you simply need to create the special markup in your react component like this:

````html
<span class="cq-text-placeholder-ipe">My Text</span>
````

The rest will be taken care of by AEM.
