### ISSUE TITLE
Question: ReactScriptEngineFactory subServiceName

### ISSUE THREAD

**Issue by khakiout** [sinnerschrader/aem-react#25]
In `ReactScriptEngineFactory` class, we have a property called `PROPERTY_SUBSERVICENAME`. It's not set in the configurable properties though. Does this mean that we are using the `resResFactory.getAdministrativeResourceResolver(null);` (See `RepositoryConnectionFactoryImpl.java`) for the services to work?

Is it okay to expose this property and have it configured in the web console?

**Comment by stemey** [comment]
Yes, it should definitely be configurable. That is a mistake. Can you create a Merge Request, please?

Thanks

**Comment by khakiout** [comment]
Thank you! 😄
