### ISSUE TITLE
AemReact is not defined

### ISSUE THREAD

**Issue by dgsunesen** [sinnerschrader/aem-react#3]
When I try to use 'Add Element' on eg. the `Accordion` component I get the following error:

`An error has occured during execution of the selected action: AemReact is not defined -> ReferenceError: AemReact is not defined`

I see that in `react-cq.js` that particular object is defined but for some reason it is not a part of the global scope.

**Comment by stemey** [comment]
Are you using the demo package as-is or have you created your own? As you said react-cq.js should be included in the page in author mode and will then create the global variable. Are you using classic UI? Are you experiencing this problem in the with the content-finder pane on the left and without?

**Comment by dgsunesen** [comment]
Alright, so it seems to work in the Classic UI but not in the new one. Thanks
