### ISSUE TITLE
AEM total page change on routing

### ISSUE THREAD

**Issue by rahulagg** [sinnerschrader/aem-react#32]
Thank you for this amazing api. It really helps a lot.

I have a question. Can you please let me know if we have a navigation on the aem page , on click of navigation link(basically routing in react) since it is an SPA. How do we can change the total content of the page.

Like if there s a page-country which contains 3 child pages, so basically on click of the navigation link on country page , it should show the total content from AEM child page, not only a section

**Comment by stemey** [comment]
Then you should not nest the detail route in a common list route but keep it as a root route:

```` 
<router>
     <Route path="/cities.html" resourceComponent={resourceComponent} component={CityListView}/>
     <Route path="/cities/{name}.html" resourceComponent={resourceComponent} component={CityView}/>
</router>
````

**Comment by rahulagg** [comment]
Thanks much
