### ISSUE TITLE
Transform function in componentRegistry not working

### ISSUE THREAD

**Issue by jdhrnndz** [sinnerschrader/aem-react#34]
I have a created a transform function to map pass the multifield values of the component dialog as a string prop, instead of a JSON object.
```
import * as resource from "aem-react-js/component/ResourceComponent";
import ServiceProxy from "aem-react-js/di/ServiceProxy";

let transformList: any = (resource: any, wrapper: resource.ResourceComponent<any, any, any>) => {
  let model: ServiceProxy = wrapper.getResourceModel("com.project.models.ListModel");

  let extractedItems: Array<string> = [];

  if (resource.items && Object.keys(resource.items).length > 0) {
    Object.keys(resource.items).map((element: any) => {
      extractedItems.push(resource.items[element].text);
    });
  }

  let newProps: any = {
    items: extractedItems,
    listItems: extractedItems,
    randomProp: "randomStringValue"
  };

  newProps["array"] = "value assigned via string literal";
  newProps.objectAccessor = "value assigned via object member notation";

  return newProps;
};

export default transform;
```

This is how I registered my component:

```
registry.registerVanilla({ component: List, transform: transformList });
```

The problem is not only the items prop not being converted into an array, but the custom props such as the randomProp and objectAccessor also doesn't show up in my React component's props. Is there something missing here?

**Comment by stemey** [comment]
It looks good to me.
Is there an error/exception in AEMs error log? 
Do you have the latest version of aem-react-js : 0.4?
Maybe  remove the call to the RequestModel and try to render it in the browser only by calling the page with parameter `serverRendering=disabled`. Calls to Models must be executed on the server, hence debugging requires an IDE like Netbeans and since there is no support for sourcemaps it can be quite annoying. Debugging in your browser is easier.

Instead of removing the call to RequestModel you could also put the return value into the cache in the init.ts. I need to look into making that easier.

**Comment by jdhrnndz** [comment]
There are a couple of errors that I've found in the error.log file
`*INFO* GET /content/project/home/playground/jcr:content/structure/par/list_component.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Resource /content/project/home/playground/jcr:content/structure/par/list_component.html not found`
`*ERROR* GET /content/intrl-unimart/home/playground.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource SyntheticResource, type=undefined, path=/content/intrl-unimart/home/playground/jcr:content/structure/par/list_component/undefined`

However, I'm not sure if it causes the problem but the component is rendering without a problem except for the missing newProps.

And, yes, i am using the latest version.

I removed the call to the RequestModel and reloaded the page with `serverRendering=disabled` param.
The code looks like this now:
```
import * as resource from "aem-react-strat/component/ResourceComponent";

let transformList: any = (resource: any, wrapper: resource.ResourceComponent<any, any, any>) => {
  let extractedItems: Array<string> = [];

  if (resource.items && Object.keys(resource.items).length > 0) {
    Object.keys(resource.items).map((key: any) => {
      if (key === "jcr:primaryType") {
        return;
      }

      extractedItems.push(resource.items[key].text);
    });
  }

  let newProps: any = {
    items: extractedItems
  };

  console.log(newProps);

  return newProps;
};

export default transformList;
```

At this point, I am sure that I have modified the data correctly to desired form since I checked it using console.log. But it is still not visible/inaccessible from the component's props.

**Comment by stemey** [comment]
Try to debug this class: https://github.com/sinnerschrader/aem-react-js/blob/master/component/WrapperFactory.tsx

It calls the transform and passes it to the vanilla component.

**Comment by jdhrnndz** [comment]
I see that newProps variable is being correctly accessed in that class however it is not being used when creating the element.

This line:
```
return React.createElement(this.config.component, props, children);
```
should use newProps, if it is not empty.

**Comment by stemey** [comment]
Please use the latest version, I see that it was fixed but not released. I will release a new version 0.4.1 as soon as possible

**Comment by stemey** [comment]
Did the release - please test

**Comment by jdhrnndz** [comment]
I suggest that instead of completely replacing the `props` variable with `newProps`, they must be merged (much like doing an Object.assign) so that we don't lose the unmodified data. 

Here's my fix:

<script src="https://gist.github.com/jdhrnndz/29ef9093e7e3442c60fdabbfc8c8e50b.js"></script>

Should I make a pull request?

**Comment by stemey** [comment]
Looks good. It is important to not modify the original props - just like you did it. I see that the original code fails to do that when merging the config.props. Can you fix that, please

Please create a Merge Request and also add/modify a test in WrapperFactoryTest to verify the new functionality https://github.com/sinnerschrader/aem-react-js/blob/master/test/WrapperFactoryTest.tsx

**Comment by jdhrnndz** [comment]
Good day!
I have encountered another problem in using this transform approach. Whenever I put aem components via a cq:template/component template, the transform function doesn't get called. There isn't any problem when I drag the components into a parsys. I just want to ask if this is the limitation of this feature or just a bug? Thanks!

**Comment by stemey** [comment]
I tried to define default values via cq:template for the example textfield vanilla component and it worked right away. The transform was also called. What AEM version are you using?

**Comment by jdhrnndz** [comment]
I am using *AEM 6.1*

This is what the cq:template looks like:

```
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0"
          xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
          xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
          jcr:primaryType="cq:Page">
    <jcr:content
            cq:lastModified="{Date}2017-03-05T01:27:07.264+08:00"
            cq:lastModifiedBy="admin"
            cq:template="/apps/my-project/templates/page-duo"
            jcr:primaryType="cq:PageContent"
            jcr:title="My Page"
            sling:resourceType="my-project/pages/page">
        <structure
                jcr:primaryType="nt:unstructured"
                sling:resourceType="my-project/components/structure/duo-content-page">
            <header
                    jcr:lastModified="{Date}2017-03-05T01:27:07.237+08:00"
                    jcr:lastModifiedBy="admin"
                    jcr:primaryType="nt:unstructured"
                    sling:resourceType="my-project/components/content/react/duo-header-component">
                <country-select
                        jcr:primaryType="nt:unstructured"
                        sling:resourceType="my-project/components/content/react/country-select-component"/>
            </header>
        </structure>
    </jcr:content>
<jcr:root>
```

The country-select component is the owner of the transform that wasn't called.

**Comment by stemey** [comment]
Ok, I was not aware of this functionality. I don't really understand why it behaves differently from the manual case. Are yuo using ReactParsys in the header?

**Comment by jdhrnndz** [comment]
I wasn't using ReactParss in the header. The my-header-component renders the country-select-component like this: 

```
<div>
    <CountrySelectComponent path="country-select" />
</div>
```

**Comment by stemey** [comment]
The way you include it is the problem. You cannot use the vanilla component directy. Unfortunately,  I haven't created the proper way to include the vanilla wrapper. Basically it looks something like this:

```` 
VanillaInclude extends AemComponent {

render() {
  let componentType = this.getRegistry().getComponent(this.props.resourceType);
  return React.createElement(componentType, this.props);
 }
}

```` 

Then use it like this:

````

renderBody() {
    return  (<div><VanillaInclude resourceType="......" props={...props}/></div>);
}

````

It should also be possible to not define resourceType but the vanilla component type.


Will look into it.

**Comment by jdhrnndz** [comment]
Should I use the same value as sling:resourceType in the resourceType prop? If not, what value should I use?

**Comment by stemey** [comment]
That's the idea. I am currently working on a solution with passing the vanilla class here:

https://github.com/sinnerschrader/aem-react-js/pull/30

**Comment by jdhrnndz** [comment]
Can you guide me on how to use this new feature? I'm kinda lost in the SPA implementation right now and I don't know what to modify to accommodate this change. Thanks a lot! Your help is very much appreciated :)

**Comment by stemey** [comment]
Suppose you have a vanilla component `MyComponent` that is registered via `componentRegistry.registerVanilla()` and hence is available as an AEM componet under resourcetype `X`. You want to include the AEM component in another react component. There are three ways:

1. standard aem component

````
return(<div><ResourceInclude path="test" resourceType="X"/></div>);
````
This will currently not work correctly because it will create a new react tree inside the current one - i still have to fix that.

2. react component

````
return(<div><MyComponent/></div>);
````
This will work but only the vanilla component not the AEM component will be included - it will not be editable.

3. <VanillaInclude>

````
return(<div><VanillaInclude path="test" component={MyComponent}/></div>);
````
This will include the AEM component in the current react tree.

**Comment by stemey** [comment]
closed question due to inactivity
