### ISSUE TITLE
'dialog' selector

### ISSUE THREAD

**Issue by khakiout** [sinnerschrader/aem-react#36]
Hello again,

I'm wondering if this is using the '.dialog' selector for the aem components. 

I had an issue after installing SP1/SP2 in my AEM 6.1 servers. The React components disappears after editing (to be exact, their content disappears).  This issue happen on the TouchUI edit window (editor.html). BTW, we're using **aem-react-0.4.0.**

For example, I have a React text component. During editing, the editor calls the resource again with the '.dialog' selector to rerender the content. In plain AEM 6.1 server, there is no 'dialog' selector being included, which works fine. 

Sample url being called after edit is
http://localhost:4502/content/test/home/jcr:content/structure/par/text_component.html?forceeditcontext=true&_=1489148319496 (no SP) and 
http://localhost:4502/content/test/home/jcr:content/structure/par/text_component.dialog.html?forceeditcontext=true&_=1489148319496 (SP1/SP2)

![dialog-call](https://cloud.githubusercontent.com/assets/3415132/23795250/7cf5fdd6-05cf-11e7-960c-756b4f56e33f.PNG)

Rendered properly with .dialog selector

```
<div class="parbase text content">

	<div data-react-server="true" data-react="app" data-react-id="/content/test/home/jcr:content/structure/par/text_component">
		<span data-reactroot="" data-reactid="1" data-react-checksum="1190579901">
			<p data-reactid="2"><!-- react-text: 3 -->Sample text.<!-- /react-text --><br data-reactid="4"/><!-- react-text: 5 -->
			<!-- /react-text --></p><!-- react-text: 6 -->
			<!-- /react-text -->
		</span>
	</div>

<textarea id="/content/test/home/jcr:content/structure/par/text_component" style="display:none;">{&quot;cache&quot;:... other contents...}</textarea>
<cq data-path="/content/test/home/jcr:content/structure/par/text_component" data-config="{...}"></cq>
</div>
```

This is the source output with the 'dialog' selector

```
<div class="parbase text content">

<cq data-path="/content/test/home/jcr:content/structure/par/text_component" data-config="{....}"></cq>
</div>

```

**Comment by stemey** [comment]
Which version of aem-react are you using? Can you seems them if you append ?wcmmode=disabled to the url? To debug the situation in the browser add the following parameters ?wcmmode=disabled& serverRendering=disabled. 

Need more info.

**Comment by khakiout** [comment]
@stemey updated the info now. with some code snippets. this issue has been bugging me after I updated to the SP1/2 packages.

**Comment by stemey** [comment]
The react components issue the .dialog call. But in the authorMode they should not even be instantiated in the client. So that seems to be the problem.  The check which prevents instantiation is here:

https://github.com/sinnerschrader/aem-react-js/blob/master/ComponentManager.tsx#L44

Try to debug this and see why it is not working as expected, please.

**Comment by stemey** [comment]
My last assessment was probably not correct. the dialog call was issued by AEM javascript as far as I understand. I don't know why, though. Is it a coincidence that aem-react uses that selector for rendering the wrapper element? Or is it a result? I don't know. Is this dialog selector also being used for normal sightly components when updating them? If so then it is a coincidence and we need to use a more specific selector or make it configurable.

**Comment by khakiout** [comment]
Hmmm.. At first I thought it was AEM calling it, but it seems unlikely. I tested my other applications (both JSP and sightly components) on SP1/SP2, and the 'dialog' selector isn't being included.

**Comment by stemey** [comment]
I currently at a loss why this is happening. The dialog selector is used in the server to get the wrapper element of a react component. The client does not use it.

Can you try an xhr break point to pin down the code that issues the call?
Also post the rendered html of the component. It might be something special about the extra elements generated by AEM to provide the author mode ui.

**Comment by khakiout** [comment]
Stuck here. Can you point where does the `<cq data-config="{...}">` gets generated? It has different contents after SP1 update. One thing is that with SP1/2, it contains an additional property called `slingPath` (this contains the url with 'dialog' selector). This might lead to a clue.

**Comment by stemey** [comment]
I understand the problem now. I will look into a fix. Here are the two pieces of code that need to be changed:

https://github.com/sinnerschrader/aem-react/blob/master/core/src/main/java/com/sinnerschrader/aem/react/ReactScriptEngine.java#L90

https://github.com/sinnerschrader/aem-react/blob/master/core/src/main/java/com/sinnerschrader/aem/react/api/Sling.java#L263

I will look into a different mechanism to render the wrapper element only.

**Comment by stemey** [comment]
please if the pull request fixes your problem.

**Comment by khakiout** [comment]
Thanks! the fix works.

**Comment by stemey** [comment]
to get the wrapper element from AEM a request is dispatched to the component. In this request only the wrapper is rendered and the ReactScriptEngine renders nothing. To distinguish these two cases we used a dialog selector before and now we just set a request attribute. The request attribute is set to its old value in the above code snippet. That's it.
