### ISSUE TITLE
Issue running: incorrect reference to client.js

### ISSUE THREAD

**Issue by gregorskii** [sinnerschrader/aem-react#48]
Hi there,

Found an issue when the project is built, it looks like the the page.html:

https://github.com/sinnerschrader/aem-react/blob/master/demo/src/main/content/jcr_root/apps/react-demo/pages/page/page.html#L17

Is referencing an old version of the main JS file `react.demo` where the correct file is `client`:

```
<meta data-sly-call="${clientlibInclude.js @ categories='client'}" data-sly-unwrap />
```

**Comment by stemey** [comment]
When the project is built, then client.ts and all dependent typescript files are bundled and stored in `/etc/designs/react-demo/js/react-demo/app.js`. Tha file is included via js.txt into the clientLib and made available as react-demo.js by AEM. Maybe you didn't build the project correctly.

**Comment by gregorskii** [comment]
Hm, ok, will look into that, I used the build command provided by the readme website with the profile autoInstallPackages against the code in this readme.

In the project I am testing this for I do not let aem process the scripts and CSS in clientlibs, but I was testing this with the demo project directly, and not using my actual project. In my project I do not produce the js.txt files, or context.xml files to allow aem to see that it needs to compress js or css.

**Comment by gregorskii** [comment]
This was fixed by using the Archetype.
