### ISSUE TITLE
Render components in a non-AEM context/environment

### ISSUE THREAD

**Issue by dgsunesen** [sinnerschrader/aem-react#5]
Hi,

So to have some rapid component development, I'm using React Storybook (https://github.com/kadirahq/react-storybook) and it works great. I have it working with typescript like this:

```
import * as React from 'react'

interface IButtonProps {
  clickHandler?: () => void
  propText? : string
}

export default class Button extends React.Component<IButtonProps, any> {

  constructor(props : IButtonProps) {
    super(props)
  }

  public render() : React.ReactElement<any> {
    const { clickHandler, propText } = this.props
    const text = propText ? propText : 'My text'

    return <button onClick={clickHandler}>{text}</button>
  }
}
```

However, when I try and extend `ResourceComponent`instead like the following: 

```
import * as React from 'react'
import { ResourceComponent, Resource, ResourceProps } from 'aem-react-js/component/ResourceComponent'

interface IButtonProps extends ResourceProps<any> {
  clickHandler?: () => void
  propText? : string
}

export default class Button extends ResourceComponent<any, IButtonProps, any> {

  constructor(props : IButtonProps) {
    super(props)
  }

  public renderBody() : React.ReactElement<any> {
    const { clickHandler, propText } = this.props
    const text = propText ? propText : 'My text - bla bla'

    return <button onClick={clickHandler}>{text}</button>
  }
}
```

```
Error: Cannot read property 'registry' of undefined
Button.ResourceComponent.getResourceType
webpack:///~/aem-react-js/component/ResourceComponent.js:63:39
Button.ResourceComponent.render
webpack:///~/aem-react-js/component/ResourceComponent.js:41:144
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext
webpack:///~/react/lib/ReactCompositeComponent.js:587:34
ReactCompositeComponentMixin._renderValidatedComponent
webpack:///~/react/lib/ReactCompositeComponent.js:607:32
wrapper [as _renderValidatedComponent]
webpack:///~/react/lib/ReactPerf.js:66:21
ReactCompositeComponentMixin.mountComponent
webpack:///~/react/lib/ReactCompositeComponent.js:220:30
wrapper [as mountComponent]
webpack:///~/react/lib/ReactPerf.js:66:21
Object.ReactReconciler.mountComponent
webpack:///~/react/lib/ReactReconciler.js:37:35
ReactCompositeComponentMixin.mountComponent
webpack:///~/react/lib/ReactCompositeComponent.js:225:34
wrapper [as mountComponent]
webpack:///~/react/lib/ReactPerf.js:66:21
```

and

![screen shot 2016-04-12 at 15 00 47](https://cloud.githubusercontent.com/assets/1023815/14460736/65bb876e-00bf-11e6-888b-c7d9577e7040.png)

I am just wondering if there is a way to have my AEM-react components render and live outside of AEM for testing/development purposes?

**Comment by stemey** [comment]
You can use your external non-AEM component as a child of a generic ResourceComponent instead of extending ResourceComponent. ResourceComponent basically sets up the context to make the current resource and path available to all children.

**Comment by dgsunesen** [comment]
Okay, so once I have a component that's ready for production/AEM then let it extend the 'real' ResourceComponent afterwards in production? Or have I misunderstood you?

**Comment by stemey** [comment]
Imagine you have a vanilla react component text. It has a 'value' prop. You want the value to be the 'text' prop of the current resource. Then you do the following:
````js
render() {
   return (<genericResourceComponent><text value={this.context.resource.text}></text></genericResourceComponent>
}

````

GenericResourceComponent basically just renders `this.props.children`.

**Comment by dgsunesen** [comment]
Alright, I get you. But where does that take me once I want that particular component to be wired up with all the neat AEM stuff already in place within the original ResourceComponent and built through maven into AEM? Sorry for all the questions, I am just trying to wrap my head around this :-)

**Comment by dgsunesen** [comment]
The `GenericResourceComponent` shouldn't that extend either `AemComponent` or `ResourceComponent` in order to benefit from all the AEM methods, context and so on?

**Comment by dgsunesen** [comment]
```
import * as React from 'react'

interface IGenericResourceComponentProps extends React.Props<GenericResourceComponent> {
}

export default class GenericResourceComponent extends AemComponent<IGenericResourceComponentProps, any> {
  constructor(props : IGenericResourceComponentProps) {
    super(props)
  }

  render() : React.ReactElement<any> {
    const { children } = this.props
    return <div>
      { children }
    </div>
  }
}
```

Like so?

**Comment by stemey** [comment]
I'd probably extend ResourceComponent which is similar to <cq:include>.

**Comment by dgsunesen** [comment]
How would I combine `React.Props` with the ResourceComponent.. It seems to require it to have `ResourceProps`.. I am using ´React.Props` so that I am able to render children.
