### ISSUE TITLE
having trouble while binding click event

### ISSUE THREAD

**Issue by rameshreddy89** [sinnerschrader/aem-react#55]
i am trying to bind the click event in the tsx html, but the event is not binding to corresponding html.
i can see my function code in the source (compiled) file..

**Comment by stemey** [comment]
Remember that javascript is disabled in author mode. Disable author mode by adding parameter wcmmode=disabled or setting the corresponding cookie.
Use React Dev Tools to analyze the problem.

**Comment by rameshreddy89** [comment]
Thanks stemey,

**wcmmode=disabled** is working..
