### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by sovanyio** [sinnerschrader/aem-react#60]
I might be jumping the gun here, but I forked the project and got React v16 working. Are there plans to upgrade to v16 here?

I also added support to toggle client hydration for author mode, which was needed for my projects.

Fork here: https://github.com/sovanyio/aem-react-js

**Comment by stemey** [comment]
You are welcome to fork and the create a pull request. Although there hasn't been a lot of activity lately, we will soon create a huge MR with lots of new features and bug fixes. React 16 is also on our roadmap.

**Comment by sovanyio** [comment]
Alright that sounds good. I'll create the PR for my fork then.
