### ISSUE TITLE
Performance and concurrency

### ISSUE THREAD

**Issue by mlucchini** [sinnerschrader/aem-react#7]
Hi,

I'm looking at this project from a performance point of view. My first load-testing experiments seem to show that requests involving React server-side rendering get increasingly slower with increased concurrency - two orders of magnitude slower with just about twenty concurrent requests and it gets worse.

I'm not sure what's the root cause for that, but I've tried replacing the engine pool with ThreadLocal engines and it seemed to behave better, as Jetty seems to keep its pool of threads anyway - and engines don't get instantiated and warmed too often.

Have you noticed any performance issue of that kind when using aem-react? Do you expect the caching mechanisms in AEM - perhaps the Dispatcher - to amortise the cost of rendering the content dynamically? Is that a non-issue in practice?

**Comment by stemey** [comment]
Really interesting observation. 

I would expect, that the thread local engines exhibit pretty much the same performance as the pooled engines as long as the pool is as large as the aem's concurrent request thread pool. So the difference probably have a different reason.

There is a dev mode which reloads all javascript on every request. That can take really long and might also cancel the positive performance effect of the warming up of the nashorn engines. In the future the reloading should observe changes to the actual jcr resources representing the javascript libs.

Have you run the Pool with reloadScripts set to false? The configuration is here: [ReactScriptEngineFactory.xml](https://github.com/sinnerschrader/aem-react/blob/master/demo/src/main/content/jcr_root/apps/react-demo/config/com.sinnerschrader.aem.react.ReactScriptEngineFactory.xml)

**Comment by mlucchini** [comment]
Indeed. I had noticed the `reloadScripts` configuration parameter but I was convinced I had set it to false.
It is a lot more responsive now.

Thanks!
