### ISSUE TITLE
No such function renderReactComponent

### ISSUE THREAD

**Issue by adigandra** [sinnerschrader/aem-react#9]
When any of the react-demo components are loaded on the page, I get a java error saying that no such function renderReactComponent.  
<img width="882" alt="screen shot 2016-09-09 at 1 09 30 pm" src="https://cloud.githubusercontent.com/assets/8547648/18397638/b7bef0b0-768e-11e6-8bd7-afeae22c8905.png">

I followed the steps in the readme and got the mvn to successfully build.

Let me know if I can provide any additional details.

**Comment by stemey** [comment]
Check the following:


- the  file /etc/designs/react-demo/js/react-demo/server.js exists
- Check configuration of ReactScriptEngine in webconsole:
 - go to /system/console/configMgr
 - search for "react" in the browser 
 - open the configuration. it should like the screenshot.
 - *important*: jcr path = /etc/designs/react-demo/js/react-demo/server.js/jcr:content
 - if it is not then update it. 



<img width="1167" alt="bildschirmfoto 2016-09-10 um 10 13 43" src="https://cloud.githubusercontent.com/assets/1496787/18409024/5b9e1368-773f-11e6-8f27-7c22883bde61.png">
